services:
  receipt-ocr:
    build: .
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: '1gb'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "5000:5000"
    volumes:
      - ./workspace:/workspace
      - ./testing:/testing
      - ./app:/app
    stdin_open: true
    tty: true
